// anuglar-app/src/app/app.component.ts
import { Component } from '@angular/core';
import './web-components/search-result.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  search: any;
}

<div class="App">
  <h1>Angular Web-Component Prototype</h1>

  <input placeholder="Enter your search request" [(ngModel)]="search" />

  <div class="search-print">Your search request: {{ search }}</div>

  <search-result [attr.search-attribute]="search"></search-result>
</div>

// react-app/src/App.js
import './App.css';
import { useState } from 'react';
import './web-components/search-result';


function App() {
  const [search, setSearch] = useState('');

  return (
    <div className="App">
      <h1>React Web-Component Prototype</h1>

      <input 
        placeholder = "Enter your Search request"
        onChange={(event) => setSearch(event.target.value)}
        value={search}
        >
      </input>
      
      <div className="search">Your search request: {search}</div>

      <search-result search-attribute={search}></search-result>
    </div>
  );
}

export default App;
